sudo: false
language: node_js
node_js: stable
env:
  global:
    - GH_USER_EMAIL="azuciao@gmail.com"
    - GH_USER_NAME="azu"
after_success:
  - |
        $(npm bin)/set-up-ssh --key "$encrypted_c8823eb33f4d_key" \
                             --iv "$encrypted_c8823eb33f4d_iv" \
                             --path-encrypted-key ".travis/github_deploy_key.enc"

        $(npm bin)/update-branch --commands "npm run build:website" \
                                 --commit-message "Update website [skip ci]" \
                                 --directory "website/public" \
                                 --distribution-branch "gh-pages" \
                                 --source-branch "master"